import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOption } from "../api/auth/[...nextauth]/route";
import SidebarNav from "@/components/layouts/SidebarNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Tree",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  const session = await getServerSession(authOption);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <aside className="h-screen max-h-screen w-48 flex-shrink-0 overflow-auto bg-white p-4 pt-8 shadow">
            <div className="relative mx-auto mb-8 h-[128px] w-[128px] overflow-hidden rounded-full">
              <Image
                src={session?.user?.image!}
                alt="profile-picture"
                fill
                className="h-full w-full object-cover object-center"
              />
            </div>

            <SidebarNav />
          </aside>

          <main className="max-h-screen flex-grow overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
