import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOption } from "../api/auth/[...nextauth]/route";
import SidebarNav from "@/components/navigations/SidebarNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Tree",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  const session = await getServerSession(authOption);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <aside className="h-screen max-h-screen w-48 overflow-auto bg-white p-4 shadow">
            <div className="mx-auto mb-12 h-28 w-28 overflow-hidden rounded-full">
              <Image
                src={session?.user?.image!}
                alt="profile-picture"
                width={128}
                height={128}
                className="rounded-full"
              />
            </div>

            <SidebarNav />
          </aside>

          <main className="max-h-screen flex-grow overflow-auto">
            <div className="m-8 bg-white p-4 shadow">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
